spring:
  application:
    name: api-users
  zipkin:
    base-url: http://zipkin:9411

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-security:8000

server:
  port: 9090
  forward-headers-strategy: framework

azure:
  cosmos:
    database: tkahidb
    populate-query-metrics: false
    uri: https://ahi-bha-cosmos-uat.documents.azure.com:443/
    key: dpVzoE5EA245pCSrOEVWPvRkAjysY6nUUJMgnOPn0UVPrU94dr0LzKKU9FLVkEnaIrl8YkistoaiACDbTwDYew==


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /users/v3/api-docs
  swagger-ui:
    enabled: false

#springdoc:
#  cache:
#    disabled: true