spring:
  application:
    name: api-users
  zipkin:
    base-url: http://zipkin:9411

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-security:8000
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000

server:
  port: 9090
  forward-headers-strategy: framework


azure:
  cosmos:
    database: ${database}
    uri: ${uri}
    key: ${key}
    populate-query-metrics: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /users/v3/api-docs
  swagger-ui:
    enabled: false

#springdoc:
#  cache:
#    disabled: true