spring:
  application:
    name: api-users
  zipkin:
    base-url: http://localhost:9411

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-security:8000

server:
  port: 9090
  forward-headers-strategy: framework

azure:
  cosmos:
    database: asset-demo
    populate-query-metrics: false
    uri: https://asset.documents.azure.com:443/
    key: MFgipI6p9wdKtLneLURJH0uxCSXhLJ0uvf6M37EiIWF4SrR5EMeYEnBIYQyiRUSsmE4RBNBjY9xeACDbxYkmxw==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /users/v3/api-docs
  swagger-ui:
    enabled: false

#springdoc:
#  cache:
#    disabled: true

