server:
  port: 8088
spring:
  application:
    name: api-notifications
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/notifications
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

rabbitmq:
    exchange:
      internal: internal.exchange
    queues:
      notification: notification.queue
    routing-keys:
      internal-notification: internal.notification.routing-key

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /notifications/v3/api-docs
  swagger-ui:
    enabled: false