spring:
  application:
    name: api-security
  zipkin:
    base-url: http://zipkin:9411

auth-issuer: http://api-security:8000

server:
  port: 8000
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /security/v3/api-docs
  swagger-ui:
    enabled: false