server:
  port: 8001
  servlet:
    context-path: /spring-graphql-query

graphql:
  extended-scalars: BigDecimal, Date

spring:
  graphql:
    path: /customers-graphql
    schema:
      printer:
        enabled: true
      locations: classpath:graphql/
    graphiql:
      enabled: true # Docs can be accessed http://localhost:8001/spring-graphql-query/graphiql?path=/spring-graphql-query/customers-graphql

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /spring-graphql-query-doc/v3/api-docs
  swagger-ui:
    enabled: false